name: Bug Report
description: Report a bug in DRAFT Protocol
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! If this is a **governance bypass** (gate passed when it shouldn't have), please mark it as critical.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
      placeholder: "When I called draft_gate after confirming all fields, it still returned BLOCKED..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. `pip install draft-protocol`
        2. `python -c "from draft_protocol import classify_tier; print(classify_tier('...'))"` 
        3. See error...
    validations:
      required: true

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      options:
        - stdio (MCP)
        - SSE
        - streamable-http
        - REST API
        - Library (import)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Is this a governance bypass?
      options:
        - Normal bug
        - Governance bypass (gate failed to block)
        - Security issue (see SECURITY.md instead)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `python -c "import draft_protocol; print(draft_protocol.__version__)"`
      placeholder: "0.1.0"

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.13"

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste any relevant error messages.
      render: shell
