name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What gap or limitation are you hitting?
      placeholder: "I need DRAFT to support X because currently I have to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - MCP server (tools)
        - REST API
        - Chrome extension
        - Engine (classification/mapping)
        - Providers (LLM/embedding)
        - Storage
        - Documentation
        - Docker/deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true
